### ISSUE TITLE
How to use the mipnerf config to train

### ISSUE THREAD

**Issue by languorous-cat** [yzslab/nerflab#1]
I have tried the following command
```
python train.py \
  --config configs/mipnerf.yaml \
    configs/nerflab.yaml \
  --dataset-path ../hy-tmp/garden/ \
  --exp-name garden-mip
```
However, training doesn't seem to be running correctly.

**Comment by yzslab** [comment]
Hi, try to place `mipnerf.yml` after other config files, because the values in latter config file will override the former one:
```bash
python train.py \
  --config configs/blender.yaml \
    configs/mipnerf.yaml \
  --dataset-path ~/dataset/nerf_synthetic/lego \
  --exp-name lego_mipnerf
```

**Comment by languorous-cat** [comment]
Thanks for your reply! I run the command you provided, but for some reason, the program will be killed.
![image](https://github.com/yzslab/nerflab/assets/102584561/bd56622c-72d7-4b84-8a53-39ea479fc2f0)
And I want to know, for the mipnerf 360 dataset, what config should I use to run it. If it is possible, I would like to know what the specific command is.

**Comment by yzslab** [comment]
> Thanks for your reply! I run the command you provided, but for some reason, the program will be killed. ![image](https://user-images.githubusercontent.com/102584561/239747855-bd56622c-72d7-4b84-8a53-39ea479fc2f0.png) And I want to know, for the mipnerf 360 dataset, what config should I use to run it. If it is possible, I would like to know what the specific command is.

Hi, 
I think it was killed by OOM, you can find some OOM related entries in `/var/log/syslog`. Change `blender_half_resolution` to `true` [(configs/blender.yaml#L4)](https://github.com/yzslab/nerflab/blob/acc26c5e3705c69558e5d35c98249e41506cb416/configs/blender.yaml#L4) may solve this problem (or add parameter `--config-values 'blender_half_resolution=true'` when running `train.py`).

The dataset format of mipnerf 360 is LLFF, so you should use `llff.yaml`:
```bash
python train.py \
  --config configs/llff.yaml \
  --dataset-path PATH_TO_MIPNERF360_DATASET \
  --exp-name mipnerf360
```
Besides, add `configs/use_disp.yaml` may improve the reconstruction quality for real world scenes:
```bash
...
  --config configs/llff.yaml \
    configs/use_disp.yaml \
...
```
